apiVersion: v1
kind: Secret
metadata:
  name: default-server-secret
  namespace: nginx-ingress
type: kubernetes.io/tls
data:
  tls.crt: $ytrg
  tls.key: $gfsca

# Stored in aws secrets manager